export interface AccountInvoice {
    Company: string,
    InvoiceNo: string,
    InvoiceType: string,
    InvoiceDate: string,
    CustomerPONo: string,
    SalesOrderNo: string,
    OrderType: string,
    ShipToCode: string,
    ShipToName: string,
    ShipToCity: string,
    ShipToState: string,
    ShipToZipCode: string,
    ShipToCountryCode: string,
    TaxableSalesAmt: number,
    NonTaxableSalesAmt: number,
    DiscountAmt: number,
    FreightAmt: number
}

export interface InvoiceHistoryHeader {
    InvoiceNo: string,
    HeaderSeqNo: string,
    InvoiceType: string,
    InvoiceDate: string,
    SalesOrderNo: string,
    OrderDate: string,
    OrderType: string,
    OrderStatus: string,
    ARDivisionNo: string,
    CustomerNo: string,
    TaxSchedule: string,
    BillToName: string,
    BillToAddress1: string,
    BillToAddress2: string,
    BillToAddress3: string,
    BillToCity: string,
    BillToState: string,
    BillToZipCode: string,
    BillToCountryCode: string,
    ShipToCode: string,
    ShipToName: string,
    ShipToAddress1: string,
    ShipToAddress2: string,
    ShipToAddress3: string,
    ShipToCity: string,
    ShipToState: string,
    ShipToZipCode: string,
    ShipToCountryCode: string,
    ShipDate: string,
    ShipVia: string,
    CustomerPONo: string,
    FOB: string,
    WarehouseCode: string,
    TermsCode: string,
    TermsCodeDesc: string,
    SalespersonDivisionNo: string,
    SalespersonNo: string,
    InvoiceDueDate: string,
    DiscountDueDate: string,
    AmountSubjectToDiscount: number,
    DiscountAmt: number,
    TaxableSalesAmt: number,
    NonTaxableSalesAmt: number,
    SalesTaxAmt: number,
    FreightAmt: number,
    NumberOfPackages: number,
    UserCreatedKey:string,
    Comment:string,
    EmailAddress:string,
    UDF_PROMO_DEAL:string,
    UDF_CANCEL_DATE:string,
    BillToDivisionNo:string,
    BillToCustomerNo:string
}

export interface PaperlessLogRow {
    Directory: string,
    Filename: string,
    DateCreated: string,
    TimeCreated: string,
    Sent: string,
}

export interface InvoiceHistoryDetail {
    DetailSeqNo: string,
    ItemCode: string,
    ItemType: string,
    ItemCodeDesc: string,
    QuantityOrdered: number,
    QuantityShipped: number,
    QuantityBackordered: number,
    UnitPrice: number,
    LineDiscountPercent: number,
    ExtensionAmt: number,
    PriceLevel: string,
    KitItem: string,
    ExplodedKitItem: string,
    CommentText: string,
    UnitOfMeasure: string,
    UnitOfMeasureConvFactor: number,
    StandardUnitPrice: number,
    SuggestedRetailPrice: number,
    Valuation: string,
    UDF_UPC: string,
    UDF_UPC_BY_COLOR: string,
    InactiveItem: string,
    ProductType: string
}

export interface InvoiceTrackingRecord {
    PackageNo:string,
    TrackingID:string,
    StarshipShipVia:string,
    Weight:number,
}


export interface ExtendedInvoice extends InvoiceHistoryHeader {
    Paperless: PaperlessLogRow[],
    Detail: InvoiceHistoryDetail[],
    Track: InvoiceTrackingRecord[],
}
