export const sqlCleanup = `
    DROP TEMPORARY TABLE IF EXISTS c2.TEMP_SA_Customers;
    DROP TEMPORARY TABLE IF EXISTS c2.TEMP_SA_ShipTo;
    DROP TEMPORARY TABLE IF EXISTS c2.TEMP_SA_Items;
    DROP TEMPORARY TABLE IF EXISTS c2.TEMP_SA_Accounts;
`
